query NODE($nodeId: String) {
  results: nodes(where: {id: {_eq: $nodeId}}) {
    id type_id
    out(distinct_on: [type_id]) {
      id type_id to_id
    }
    in(distinct_on: [type_id]) {
      id type_id from_id
    }
    to_id
    to {
      id type_id
    }
    from_id
    from {
      id type_id
    }
  }
}
