query NODES($where: nodes_bool_exp, $limit: Int) {
  results: nodes(where: $where, limit: $limit) {
    id type_id
    out(distinct_on: [type_id]) {
      id type_id to_id
    }
    in(distinct_on: [type_id]) {
      id type_id from_id
    }
    to_id
    to {
      id type_id
    }
    from_id
    from {
      id type_id
    }
  }
}